set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g mouse on
set -g history-limit 100000
set -sg escape-time 0
set -g focus-events on

setw -g mode-keys vi

set -g status-style bg=#1F1F28,fg=#DCD7BA
set -g pane-border-style fg=#54546D
set -g pane-active-border-style fg=#7E9CD8
set -g mode-style bg=#2D4F67,fg=#DCD7BA

setw -g window-status-style fg=#727169,bg=#1F1F28
setw -g window-status-current-style fg=#E6C384,bg=#1F1F28,bold

unbind &
bind & kill-window

unbind x
bind x kill-pane

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display-message "Reloaded"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind R command-prompt "rename-session %%"
bind n command-prompt "rename-window %%"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

source-file ~/.config/tmux/vague.conf

run '~/.tmux/plugins/tpm/tpm'
