set -g base-index 1
set -g prefix C-a
setw -g pane-base-index 1
set -g status-right ""

unbind-key &
bind-key & kill-window

unbind-key x
bind-key x kill-pane

unbind %
unbind '"'
bind v split-window -h
bind V split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key r command-prompt "rename-window %%"
bind-key R command-prompt "rename-session %%"

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-256color:RGB'
set-option -g status-bg colour235   
set-option -g status-fg colour250   

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set-option -sg escape-time 10
set-option -g focus-events on

setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"

run '~/.tmux/plugins/tpm/tpm'
