set -g prefix C-a

unbind C-b

bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g mouse on
set -g history-limit 100000
set -sg escape-time 0
set -g focus-events on

setw -g mode-keys vi

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display-message "Reloaded"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

source-file ~/.config/tmux/theme.conf

run '~/.tmux/plugins/tpm/tpm'
