set -g status-style "fg=#a9b1d6,bg=#16161e"

set -g message-style "fg=#16161e,bg=#7aa2f7"
set -g message-command-style "fg=#16161e,bg=#7aa2f7"

set -g mode-style "fg=#16161e,bg=#7aa2f7"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status-right "%Y-%m-%d %H:%M"

setw -g window-status-style "fg=#a9b1d6,bg=#16161e"
setw -g window-status-current-style "fg=#16161e,bg=#7aa2f7,bold"

setw -g window-status-activity-style "fg=#e0af68,bg=#16161e,bold"
setw -g window-status-bell-style "fg=#f7768e,bg=#16161e,bold"

setw -g clock-mode-colour "#7aa2f7"

setw -g window-status-current-format " #I:#W "
