# Status bar
set -g status on
set -g status-interval 1
set -g status-left-length 100
set -g status-right-length 100
set -g status-justify left

set -g status-style "fg=#cdcdcd,bg=#1c1c24"
set -g message-style "fg=#252530,bg=#aeaed1"

set -g status-right "#[fg=#cdcdcd,bg=#1c1c24] %a %d %b %H:%M:%S "

setw -g window-status-separator " "
setw -g window-status-format "#[fg=#878787,bg=#1c1c24] #I:#W "
setw -g window-status-current-format "#[fg=#f3be7c,bg=#1c1c24] #I:#W "

set -g mode-style "fg=#252530,bg=#f3be7c"

set -g pane-border-style "fg=#333738"
set -g pane-active-border-style "fg=#aeaed1"
