gui:
  nerdFontsVersion: ""
  showIcons: false
  mouseEvents: true
  timeFormat: "02 Jan 06"
  shortTimeFormat: "15:04"
  showRandomTip: false
  showFileTree: true
  border: "rounded"
  scrollHeight: 2
  skipDiscardChangeWarning: false
  refreshRate: 10
theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
refresher:
  refreshInterval: 10
update:
  method: never
confirmOnQuit: false
disableStartupPopups: true
notARepository: "quit"
os:
  editPreset: nvim
customCommands: []
