require("config.lsp.clangd")
require("config.lsp.rust_analyzer")
require("config.lsp.pyright")
require("config.lsp.luals")
require("config.lsp.tsserver")
require("config.lsp.jsonls")
require("config.lsp.cmake")
